<?php return [
    'status'=>[
        'v1'=>[
            'processing',
            'cancelled',
            'shipped',
            'delivered',
            'completed',
        ]
    ],
    'purchase_status'=>[
        'v1'=>[
            'unpaid',
            'paid',
        ]
    ],
    'payment_method'=>[
        'v1'=>[
            'COD',
            'bank',
        ],
        'v1_2'=>[
            'COD',
            'bank',
            'piopiayay',
        ]
    ]
];